//Sam Kriegsman

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

public class HighDivTriNum {
  public static void main(String[] args) {

    boolean numFactors = false;
    int i = 1;

    while(!numFactors) {
      //Creates Triangular Number
      int triNum = 0;
      for(int count = 1; count <= i; count++) {
        triNum += count;
      }

      //Find number of factors
      int num = 0;
      for(int j = 1; j <= triNum; j++) {
  			if(triNum%j == 0) {
  				num++;
        }
  		}

      //Checks if more than 500 factors
      if(num >= 500) {
        numFactors = true;
        System.out.println(num);
      }
      i++;
      System.out.println("TriangularNum: "+triNum+" has "+num+" factors.");
    }
  }
}

//Answer: 76576500   --> Took 15min or so to run
